
const idToTitle = {
    "9ZUniR1uQcUC": "1940",
    "FxkeEAAAQBAJ": "We the Fallen People",
    "SZjFDwAAQBAJ": "The Napoleonic Wars",
    "3YeMEAAAQBAJ": "Ring of Steel",
    "PluNEAAAQBAJ": "Flash Boys",
    "OkECDAAAQBAJ": "The Idea Factory",
    "29uwzgEACAAJ": "The Fed Unbound",
    "2G2TlJOhGI8C": "The Making of the Atomic Bomb",
    "05Cj67qkoaoC": "The Silmarillion",
    "JxpdEAAAQBAJ": "Chip War",
    "dNs33Q1cAX0C": "How Asia Works",
    "BE1QCgAAQBAJ": "The Invisible Bridge",
    "p9Y7EAAAQBAJ": "The Jesuits",
    "CA-PDAAAQBAJ": "Last and First Men",
    "toXgAAAAMAAJ": "Disturbing the Universe",
    "BAo0EAAAQBAJ": "Career and Family: Women’s Century-Long Journey Toward Equity",
    "Qhh3tAEACAAJ": "The Life of Dad",
    "K547DwAAQBAJ": "Homintern",
    "4-PvMvdVqp0C": "Caliban and the Witch",
    "zOo2EAAAQBAJ": "Can the Monster Speak?",
    "r6nOYYtxzUoC": "Metaphors We Live By",
    "N5Nzm2uihkAC": "Less Than One",
    "gsszMQAACAAJ": "The Fire Next Time",
    "hUhbEAAAQBAJ": "Burn",
    "_TAMKzMJ3w4C": "Salt Sugar Fat",
    "8XKYDwAAQBAJ": "The Secret of Our Success",
    "BXc-Ke-MgAAC": "Soldier of the Mist",
    "HuA5DQAAQBAJ": "After Atlas",
    "ZWRQEAAAQBAJ": "Babel",
    "EI88oS_3fZEC": "Why Zebras Don’t Get Ulcers",
    "vHnZCwAAQBAJ": "The Body Keeps the Score",
    "ClrOkM3snioC": "Pain",
    "iYFzAwAAQBAJ": "Slouching Towards Utopia",
    "42oaCAAAQBAJ": "How the War Was Won",
    "6dt_DwAAQBAJ": "Ninth House",
    "UNxU-2s2sQYC": "Here Comes Everybody",
    "W04JCgAAQBAJ": "The Profiteers",
    "xkscAAAACAAJ": "Jim Ravel’s Theatrical Pickpocketing",
    "FCYUmAEACAAJ": "Forever Changes",
    "PAEDEAAAQBAJ": "Public Citizens",
    "OGmPEAAAQBAJ": "The Fifth Risk",
    "8BGMEAAAQBAJ": "Seeking Truth and Hiding Facts",
    "fdlYEAAAQBAJ": "Our Missing Hearts",
    "xIs8EAAAQBAJ": "See No Stranger",
    "fBXnC_qcUusC": "From The Soil",
    "puuPxMYZl3AC": "Fei Xiaotong and Sociology in Revolutionary China",
    "oNaODQAAQBAJ": "The Fractalist",
    "LPacEAAAQBAJ": "Fit Nation",
    "b4yJEAAAQBAJ": "Dreamland",
    "ahRjEAAAQBAJ": "Freedom’s Dominion",
    "FnfYzgEACAAJ": "Where Do We Go From Here",
    "8dDm7C9EFTsC": "The Trumpet of Conscience",
    "qWCnDwAAQBAJ": "The Sword and the Shield",
    "MwtFDwAAQBAJ": "A More Beautiful and Terrible History",
    "JKszDQAAQBAJ": "Dark Ghettos",
    "dqEuDwAAQBAJ": "Capital in the Twenty-First Century",
    "om2mDwAAQBAJ": "Crashed",
    "dDrGDwAAQBAJ": "Ages of American Capitalism",
    "vOAsDwAAQBAJ": "The Ethical Slut",
    "oYoqAAAAQBAJ": "Berlin Diary",
    "xVwTAQAAIAAJ": "A Royal Affair",
    "3clrAAAAIAAJ": "The Language Instinct",
    "LKZPEAAAQBAJ": "How the World Really Works",
    "OPAgEAAAQBAJ": "The Martian",
    "90wGbUGqKCgC": "Adam Bede",
    "Cd5ZjRsNj4sC": "The Seven Day Circle",
    "qnB2DwAAQBAJ": "On the Clock",
    "c7PxAwAAQBAJ": "Happy Birthday to You!",
    "gYtIDwAAQBAJ": "The Rabbit Listened",
    "wSvcDgAAQBAJ": "Here We Are",
    "eZtyDwAAQBAJ": "The Pout-Pout Fish",
    "fhIBEAAAQBAJ": "Noise",
    "ApvzDwAAQBAJ": "When We Cease to Understand the World",
    "PrEhzgEACAAJ": "The Age of A.I.",
    "GdmEDwAAQBAJ": "Invisible Women",
    "dX3HDwAAQBAJ": "Bad Blood",
    "AoonzgEACAAJ": "The World For Sale",
    "CdtPDwAAQBAJ": "Fragmented Democracy",
    "hXSYDwAAQBAJ": "Private Government",
    "SBEqEAAAQBAJ": "Dilla Time",
    "YloNDQAAQBAJ": "The German War",
    "LQpDDwAAQBAJ": "The Demon in Democracy",
    "NtA_L2ZQSUIC": "The Face of God",
    "Bmc7EAAAQBAJ": "Wastelands",
    "PY0KUnaIU5AC": "Meatonomics",
    "7_3-ko8zyZYC": "Animal Machines",
    "ERVAPnnF3gcC": "The Gilead Novels",
    "na2i2nwR9gAC": "World and Town",
    "jtoREAAAQBAJ": "Standing by Words",
    "dgLZAAAAMAAJ": "Love’s Mind",
    "iPLjUhiXAhYC": "Middlemarch",
    "iOW5AQAACAAJ": "New York 2140",
    "rUAfEAAAQBAJ": "Orwell’s Roses",
    "0J6QEAAAQBAJ": "How It Went",
    "CJJUEAAAQBAJ": "The Storm Is Here",
    "-2eEEAAAQBAJ": "Sugar Street",
    "adwjDQAAQBAJ": "Marlena",
    "3PJbEAAAQBAJ": "The Rise and Fall of the Neoliberal Order",
    "bn5XEAAAQBAJ": "Free Market",
    "j9hyEAAAQBAJ": "Adam Smith’s America",
    "ng9NEAAAQBAJ": "Popular Dictatorships",
    "tqiTEAAAQBAJ": "Spin Dictators",
    "8f2y0F2wzLoC": "The Origins of Totalitarianism",
    "ZYlZDwAAQBAJ": "The Increasingly United States",
    "01QgBQAAQBAJ": "Groundbreakers",
    "0XVPEAAAQBAJ": "The Loud Minority",
    "rFHfDwAAQBAJ": "Rock Me on the Water",
    "azlyEAAAQBAJ": "State of Terror",
    "wehCEAAAQBAJ": "Why We Did It",
    "WXeSEAAAQBAJ": "Confidence Man",
    "BXE8EAAAQBAJ": "NSFW",
    "mMkkEAAAQBAJ": "Famine: A Short History",
    "Co5VEAAAQBAJ": "Strangers to Ourselves",
    "Ebc8AwAAQBAJ": "Fullmetal Alchemist",
    "PetSYgEACAAJ": "Mechanique",
    "GWqBEAAAQBAJ": "Witch King",
    "paudDAAAQBAJ": "The Death and Life of Great American Cities",
    "l04kDwAAQBAJ": "Hitler in Los Angeles",
    "TPU1EAAAQBAJ": "Nazis of Copley Square",
    "WHtJDwAAQBAJ": "Hitler’s American Friends",
    "HuxbAAAAMAAJ": "The Oppermanns",
    "On0aJtdvNMEC": "Down in New Orleans Billy Sothern",
    "xboytgEACAAJ": "The Neapolitan Novels",
    "fi6LzgEACAAJ": "Youthquake",
    "jOvaAAAAMAAJ": "Madness and Modernism",
    "a9rt1N0AuXoC": "Of Two Minds",
    "Iis3AQAAIAAJ": "The Rise and Fall of the Third Reich",
    "vcPosgEACAAJ": "Harry Potter and The Methods of Rationality",
    "f4SFngEACAAJ": "Algorithmic Game Theory",
    "b3GYDwAAQBAJ": "Empire and Revolution",
    "mD5DAAAAIAAJ": "Scene of Change",
    "Pus2EAAAQBAJ": "A Widening Sphere",
    "qNcBEAAAQBAJ": "Making Climate Policy Work",
    "A7uZDwAAQBAJ": "How Solar Energy Became Cheap",
    "TFBTEAAAQBAJ": "The Middle Out",
    "j3ZPEAAAQBAJ": "Elite Capture",
    "Rsx1DaUHhuAC": "Chords of Change (forthcoming 2023)",
    "k6VgkA8PL6wC": "Envy Up, Scorn Down",
    "6sx8BAAAQBAJ": "The Psychology of Social Status",
    "hdc3AAAAMAAJ": "The Theory of the Leisure Class\"",
    "CAoSDAAAQBAJ": "Staring",
    "RTojBQAAQBAJ": "H is for Hawk",
    "SSLKDwAAQBAJ": "Romance in Marseille",
    "g-cwXTn1o3EC": "The Bone People",
    "CC-REAAAQBAJ": "A Fortune for Your Disaster",
    "WNTT_8NW_qwC": "The Weight of Glory",
    "OF-YSMKCVwMC": "Mere Christianity",
    "YljRDwAAQBAJ": "The Lion, the Witch and the Wardrobe",
    "6b0nRIKjYxMC": "The Resurrection of the Son of God",
    "dx1HAAAAMAAJ": "In the Age of the Smart Machine",
    "GhbvCwAAQBAJ": "The Myth of the Paperless Office",
    "KwgEHdeA-kUC": "Liquidated",
    "f408EAAAQBAJ": "Essential Labor",
    "bm-KDQAAQBAJ": "Beloved",
    "neQdEAAAQBAJ": "Ficciones",
    "Z4MTDAAAQBAJ": "The Epic of Gilgamesh translated",
    "TaI--qgb1QcC": "Moral Capital",
    "3aSiDwAAQBAJ": "The Precipice",
    "wJ0jEAAAQBAJ": "The Scout Mindset",
    "Hod0DwAAQBAJ": "Histories of the Transgender Child",
    "RNUGkAEACAAJ": "Brilliant Imperfection",
    "e62TCwAAQBAJ": "Asegi Stories",
    "9XDWAAAAMAAJ": "Amusing Ourselves to Death",
    "eLobn4WwbLUC": "Public Opinion",
    "r2EeG3aqINYC": "Mediated",
    "uYvxDwAAQBAJ": "Nobody’s Normal",
    "bZsRAAAAQBAJ": "American Psychosis",
    "nea-sRCcK84C": "Crazy",
    "lwave_qPlYUC": "Crabgrass Frontier",
    "foqmygEACAAJ": "Neighborhood Defenders",
    "PzhjEAAAQBAJ": "A Brief History of Equality",
    "9xkQEAAAQBAJ": "The Dawn of Everything",
    "d-Qi16GXlUAC": "The Echo Maker",
    "5I-qlHF3DskC": "Backlash",
    "Fts0v56J-qAC": "No More Nice Girls",
    "uyxJEAAAQBAJ": "Status and Culture",
    "QRJOEAAAQBAJ": "The Anti-Oligarchy Constitution",
    "GNtwDwAAQBAJ": "The Second Creation",
    "3qYsEAAAQBAJ": "The Turnaway Study",
    "7i87EAAAQBAJ": "Torn Apart",
    "RfhQEAAAQBAJ": "Who Decides?",
    "hnpVDwAAQBAJ": "51 Imperfect Solutions",
    "qGjBCwAAQBAJ": "Hope in the Dark",
    "krlkDwAAQBAJ": "Man’s Search for Meaning",
    "YAQEDgAAQBAJ": "You Can’t Be Neutral on a Moving Train",
    "LWpNDwAAQBAJ": "Free Soil, Free Labor, Free Men",
    "u7UYEAAAQBAJ": "Salmon P. Chase",
    "RRAqEAAAQBAJ": "What It Took to Win",
    "qjqFDgAAQBAJ": "In Shock",
    "54WEEAAAQBAJ": "Every Deep-Drawn Breath",
    "IpSBzDAPRuYC": "Mountains Beyond Mountains",
    "SgRTEAAAQBAJ": "All That She Carried",
    "9i61zgEACAAJ": "Beautiful Country",
    "kukrDQAAQBAJ": "The Invention of Nature",
    "sL4SEAAAQBAJ": "Beautiful World, Where Are You",
    "zo91Keuw-cEC": "Socialism: Past and Future",
    "x9xmAAAAMAAJ": "The Age of Extremes",
    "xuhOEAAAQBAJ": "The South",
    "FE0nDAAAQBAJ": "The Great Demarcation",
    "Y3SYDwAAQBAJ": "The Emergence of Globalism",
    "VAPVzgEACAAJ": "Classified",
    "JVFVEAAAQBAJ": "Criminal (In)Justice",
    "jTzYAgAAQBAJ": "Sir Vidia’s Shadow",
    "qCQ7EAAAQBAJ": "The Strategy of Denial",
    "6QyuJvo2km4C": "Rights Talk",
    "bkINtUVlIWEC": "Feminism Without Illusions",
    "NF3sDwAAQBAJ": "Public Man, Private Woman",
    "GONCEAAAQBAJ": "Stones",
    "7zYYEAAAQBAJ": "Frank: Sonnets",
    "xHqoywEACAAJ": "Postcolonial Love Poem",
    "FPiFDwAAQBAJ": "Beyond Roe",
    "ExHaAAAAMAAJ": "Abortion: Three Perspectives",
    "r3W5DgAAQBAJ": "About Abortion",
    "5s8DEAAAQBAJ": "Cuba",
    "FpqhEAAAQBAJ": "The Lincoln Highway",
    "Ls_GDwAAQBAJ": "The New Class War",
    "CWyGDwAAQBAJ": "Dominion",
    "Ct0REAAAQBAJ": "The Art of Loading Brush",
    "TOzQDQAAQBAJ": "Let Us Talk of Many Things",
    "64c-DwAAQBAJ": "Making It",
    "7Cq-v7M6N74C": "The Prince of Darkness",
    "wpoOEAAAQBAJ": "The Bond King",
    "woFnDwAAQBAJ": "Typeset in the Future",
    "zupKAAAAYAAJ": "The Surprise of Cremona",
    "92_bzgEACAAJ": "Free",
    "HY34DwAAQBAJ": "The Age of Unpeace",
    "_NZpzgEACAAJ": "Time Shelter",
    "dfE3EAAAQBAJ": "Scary Monsters",
    "vlNcDAAAQBAJ": "Ill Will",
    "5qoZF4xlrK4C": "Suite Française",
    "GJSOrgEACAAJ": "The Course",
    "DbSZAAAAQBAJ": "The Climate War",
    "A8DvDwAAQBAJ": "A Theory of System Justification",
    "m_JEEAAAQBAJ": "Memorial",
    "liwZEAAAQBAJ": "These Precious Days",
    "WzFCEAAAQBAJ": "Ukraine in Histories and Stories",
    "0SH6DAAAQBAJ": "The Gates of Europe",
    "RY-YDgAAQBAJ": "Lost Kingdom",
    "7gQ0DwAAQBAJ": "Chernobyl",
    "09mzzgEACAAJ": "Blood of Others",
    "fJNmtAEACAAJ": "The Art of War",
    "r9WMDQAAQBAJ": "The Power Broker",
    "lahOFhcQkggC": "The Tombs of Atuan",
    "GC7MD17YvJEC": "Persuasive Games",
    "Bq9FEAAAQBAJ": "Collapse",
    "TdHoDwAAQBAJ": "The Perfect Fascist",
    "XoIatYmBHvkC": "My Century",
    "U_WoXcJq_1wC": "The Best and the Brightest",
    "l0wlEAAAQBAJ": "The Price of Peace",
    "nDvGDwAAQBAJ": "War",
    "hpDODwAAQBAJ": "Biased",
    "xq4uEAAAQBAJ": "Secrets of the Sprakkar",
    "WwN4BgAAQBAJ": "Charlotte’s Web",
    "AVVoPwAACAAJ": "Lord of the Rings",
    "Wn9fDwAAQBAJ": "Putin’s World",
    "a3YsEAAAQBAJ": "The Power of Law",
    "q5EvEAAAQBAJ": "The Cloud Revolution",
    "jshQEAAAQBAJ": "The Economic Weapon",
    "6ghMEAAAQBAJ": "Not One Inch",
    "TE0iZ4U2ZvUC": "The Sleepwalkers",
    "U9wiBQAAQBAJ": "Nothing Is True and Everything Is Possible",
    "oe-FCgAAQBAJ": "The Last Empire",
    "lGCNEAAAQBAJ": "Manual for Survival",
    "0BCIEAAAQBAJ": "Babi Yar",
    "maEfAQAAQBAJ": "Bloodlands",
    "f2yYDwAAQBAJ": "The Limits of Partnership",
    "MthoAAAAMAAJ": "Russia Under the Old Regime",
    "IVgwEAAAQBAJ": "The Formation of the Soviet Union",
    "p2l3tgEACAAJ": "Man, the State, and War",
    "zNL5DwAAQBAJ": "A World Safe for Democracy",
    "190NEAAAQBAJ": "Memoirs 1925-1950",
    "z7QMzgEACAAJ": "The End of the End of History",
    "ZzQ4EAAAQBAJ": "The Future of Money",
    "N5IyEAAAQBAJ": "The Anarchy",
    "xRpnzgEACAAJ": "India: A Story Through 100 Objects",
    "emhaEAAAQBAJ": "The Splendid and the Vile",
    "ynVcIxs4GLsC": "Dear Parent: Caring for Infants with Respect",
    "rnhsD64KvmwC": "Siblings Without Rivalry",
    "6s607DFWiBgC": "The Hurried Child",
    "idIY9V6e7r0C": "The Anatomy of a Moment",
    "94LlexI2U90C": "Visitors\"",
    "q-yDDwAAQBAJ": "The Apology",
    "8_S6cOkHK3MC": "The Myth of the Rational Voter",
    "xB2ZDwAAQBAJ": "The Weirdest People in the World",
    "Nj6FDwAAQBAJ": "Who We Are and How We Got Here",
    "R3VCAgAAQBAJ": "Law and Disagreement",
    "KryXDwAAQBAJ": "Cult of the Constitution",
    "fzc7EAAAQBAJ": "The Heart Principle",
    "JysvEAAAQBAJ": "Olga Dies Dreaming",
    "uZ9OEAAAQBAJ": "Let’s Get Physical",
    "3EsqEAAAQBAJ": "When You Greet Me I Bow",
    "LBaaAAAAIAAJ": "The Aleph and Other Stories",
    "Vok4FxXvZioC": "Vibrant Matter",
    "pvdQDwAAQBAJ": "The Gatekeepers",
    "82fbDwAAQBAJ": "The Theory and Practice of Group Psychotherapy",
    "OoLNzl4XpPUC": "Chaos",
    "zR8DHu5A55YC": "The Dead Hand",
    "lHDRy1-m610C": "The Braindead Megaphone",
    "QxbFBAAAQBAJ": "The Three-Body Problem Series",
    "8LKdDgAAQBAJ": "The Racial Contract",
    "iBoqmEvavawC": "Nicomachean Ethics",
    "w4NIsg8KtM0C": "The Hebrew Bible, especially Genesis and Exodus",
    "elRRDwAAQBAJ": "Democracy in America",
    "RdkNAAAAQAAJ": "Daniel Deronda",
    "6m7cDwAAQBAJ": "The Sum of Us",
    "OT-dEAAAQBAJ": "Caste",
    "w5EcCgAAQBAJ": "Being Mortal",
    "ZuKTvERuPG8C": "Thinking, Fast and Slow",
    "R5KADwAAQBAJ": "Enlightenment Now",
    "Isa2wAEACAAJ": "Perception and Misperception in International Politics",
    "-hPEbxIgKVEC": "The Stickup Kids",
    "N_tVVPXLfMIC": "The Truly Disadvantaged",
    "oELznQEACAAJ": "Siddhartha",
    "bKXvzAEACAAJ": "Lost in Work",
    "sDWFFlNv-5IC": "Farewell to the Factory",
    "P8GGDwAAQBAJ": "Confessions of the Fox",
    "SoXUDAAAQBAJ": "Fortress America",
    "wdEpDgAAQBAJ": "Future Home of the Living God",
    "b_HKDwAAQBAJ": "Tiny You",
    "rVjYU5EMDQoC": "The Boys on the Bus",
    "X61iAAAAMAAJ": "Making News",
    "bWpFtVJlAD0C": "Deciding What’s News",
    "6Kz7DwAAQBAJ": "South to America",
    "EskTEAAAQBAJ": "Shoutin’ in the Fire",
    "OdBvzgEACAAJ": "Abolition for the People",
    "s6A4DwAAQBAJ": "The Color of Money",
    "c3MADAAAQBAJ": "A Pound of Flesh",
    "FZMUswEACAAJ": "The Adventures of Tintin",
    "VQwq4_h-M3IC": "The Charterhouse of Parma",
    "lXM0pd6oaKsC": "The Gnostic Religion",
    "tebyDwAAQBAJ": "The Journal of a Disappointed Man",
    "JcXCAwAAQBAJ": "On Immunity",
    "w7LQDwAAQBAJ": "The Cancer Journals",
    "5VH1DwAAQBAJ": "The Love Songs of W.E.B. Du Bois",
    "teyADwAAQBAJ": "Thick",
    "Qa_MpVB06YUC": "A Midwife’s Tale",
    "8C_qCQAAQBAJ": "The Negro in the American Revolution",
    "dhM7mdH62UoC": "Rebecca’s Revival",
    "JTp2eWZCh98C": "The Company",
    "3SSOEAAAQBAJ": "My Life in Full",
    "uqFBDAAAQBAJ": "Palace Walk",
    "zeAREAAAQBAJ": "Fidelity",
    "g1jIkcOH18gC": "Wanderlust",
    "3pEiDQAAQBAJ": "Girls and Sex",
    "5weYDwAAQBAJ": "Boys and Sex",
    "NjRxSBP0JqYC": "Possibilities",
    "c67kzQEACAAJ": "Wayward Lives, Beautiful Experiments",
    "9ycZEAAAQBAJ": "The Force of Nonviolence",
    "CxGnCoLkt4QC": "Due Diligence",
    "CDAWBQAAQBAJ": "The Lifeways of Hunter-Gatherers",
    "TUf9DwAAQBAJ": "Healthy At Last",
    "LV76DwAAQBAJ": "Breaking The Habit of Being Yourself",
    "JWD6DwAAQBAJ": "You Are The Placebo",
    "L6bODwAAQBAJ": "Upstream",
    "XfFvDwAAQBAJ": "Atomic Habits",
    "zgPyDwAAQBAJ": "How to Be Animal",
    "l1zZzQEACAAJ": "Rooted",
    "HUM3EAAAQBAJ": "Ever Green",
    "MzZwDwAAQBAJ": "How All Politics Became Reproductive Politics",
    "wJRlDwAAQBAJ": "Killing for Life",
    "hN-4DgAAQBAJ": "Radical Reproductive Justice, edited",
    "JcWWDwAAQBAJ": "The Deficit Myth",
    "Rvy0DwAAQBAJ": "Stalingrad",
    "_pMYDAAAQBAJ": "Essays in Persuasion",
    "VScwbwVi2cwC": "Love Goes to Buildings on Fire",
    "aPZ_F0BlEjoC": "The Buddha in the Attic",
    "uTgJSDK3GSkC": "When the Emperor Was Divine",
    "yz5GAgAAQBAJ": "Mad As Hell",
    "CPElBQAAQBAJ": "Ain’t Gonna Let Nobody Turn Me Around",
    "HypyDwAAQBAJ": "Revolting Prostitutes",
    "BEoEEAAAQBAJ": "Feminist International",
    "ivkXBwAAQBAJ": "Undoing the Demos",
    "DTeDDwAAQBAJ": "The End of the Myth",
    "CQEGEAAAQBAJ": "Difference Without Domination",
    "tmZeR-bJ53QC": "Cars and Trucks and Things That Go",
    "OE1tDwAAQBAJ": "The Hell of Good Intentions",
    "i9oIswEACAAJ": "Frankenstein",
    "PXI3swEACAAJ": "Love in Goon Park",
    "dLm5BwAAQBAJ": "The Narrow Road to the Deep North",
    "QDzOnQEACAAJ": "Reconstruction",
    "7IjA4g0kyNQC": "Black Reconstruction in America, 1860-1880",
    "Yp9GDwAAQBAJ": "Children of Blood and Bone",
    "526DDwAAQBAJ": "The City We Became",
    "OyQYDQAAQBAJ": "American War",
    "ifusDwAAQBAJ": "The Jakarta Method",
    "J8-VzQEACAAJ": "Overheated",
    "P3uPEAAAQBAJ": "The New Gods",
    "DcveoQEACAAJ": "Lazarus",
    "EWJdDwAAQBAJ": "Rise of the Black Panther",
    "tabzwAXZP6MC": "Wired for Culture",
    "bLSkDwAAQBAJ": "Rule Makers, Rule Breakers",
    "8yntDwAAQBAJ": "Stuck",
    "EgKaPwAACAAJ": "Tools for Conviviality",
    "bGlwDwAAQBAJ": "The Human Condition",
    "GdonAgAAQBAJ": "Technology and the Character of Contemporary Life",
    "dt6JDQAAQBAJ": "The Warmth of Other Suns",
    "fTY9EAAAQBAJ": "Postwar: A History of Europe Since 1945",
    "Sz02vbVtLkEC": "Avengers of the New World",
    "FFO2clqJCqMC": "Crucible of War",
    "_Igxh-pKXkkC": "Champlain’s Dream",
    "nTtjEAAAQBAJ": "Mom Genes",
    "aeUlEAAAQBAJ": "Golden Gates",
    "-DHuAAAAMAAJ": "The Dispossessed",
    "WTBA-wzX7cwC": "Stories of Your Life and Others",
    "I-tSEhdEorUC": "Supersizing the Mind",
    "lv1wDwAAQBAJ": "Mind in Motion",
    "HjPRDQAAQBAJ": "Thoughts Without a Thinker",
    "E8ViDwAAQBAJ": "Dying of Whiteness",
    "BNqsDwAAQBAJ": "Race for Profit",
    "5JKNN1ReCsUC": "The Outermost House",
    "rtHR8_gK_WwC": "The Old Way",
    "q2seF0NRfYQC": "King Solomon’s Ring",
    "YO8OEAAAQBAJ": "Chlorine Sky",
    "xKj7DwAAQBAJ": "Halfway Home",
    "7vRFDwAAQBAJ": "Severance",
    "6nYbAQAAIAAJ": "Don Quixote",
    "AQVQjI7ngVoC": "A Temple of Texts and other work",
    "3MF2DwAAQBAJ": "King Leopold’s Ghost: A Story of Greed, Terror and Heroism in Colonial Africa",
    "EJ4jEAAAQBAJ": "Entangled Life: How Fungi Make Our Worlds, Change Our Minds and Shape Our Futures",
    "CRNmDQAAQBAJ": "Other Minds: The Octopus, the Sea and the Deep Origins of Consciousness",
    "MFEajdUgSnMC": "Tinker, Tailor, Soldier, Spy",
    "UmxBmQEACAAJ": "Race and Reunion: The Civil War in American Memory",
    "gsj3DwAAQBAJ": "Dirty Work: Essential Jobs and the Hidden Toll of Inequality in America",
    "t2vMDwAAQBAJ": "Poor Queer Studies: Confronting Elitism in the University",
    "qF3IDwAAQBAJ": "Vanguard: How Black Women Broke Barriers, Won the Vote and Insisted on Equality for All",
    "794HywEACAAJ": "Memorial Drive",
    "SG6TEAAAQBAJ": "Klara and the Sun",
    "bkeNDQAAQBAJ": "The Undercover Economist Strikes Back",
    "lfrk6HmuN7EC": "Tristes Tropiques",
    "3UIryMy2hzwC": "Chance and Circumstance: Twenty Years With Cage and Cunningham",
    "vzIrAQAAIAAJ": "Crystal Nights",
    "R1XFPQAACAAJ": "The Gentle Seduction",
    "08_TDgAAQBAJ": "Root Shock",
    "hPUTEAAAQBAJ": "Poorly Understood",
    "hF_ODwAAQBAJ": "What to Expect When You’re Expecting Robots",
    "ObLBJ_w2ZlcC": "Finite and Infinite Games",
    "bxYMEAAAQBAJ": "How to Do Nothing",
    "_zQsDwAAQBAJ": "The Overstory",
    "bZXtAQAAQBAJ": "Ghettoside",
    "a7hIDwAAQBAJ": "Becoming Ms. Burton",
    "wNScDwAAQBAJ": "The Condemnation of Blackness",
    "qIPWDwAAQBAJ": "Bring the War Home: The White Power Movement and Paramilitary America",
    "jODrDwAAQBAJ": "Gods of the Upper Air: How a Circle of Renegade Anthropologists Reinvented Race, Sex and Gender in the Twentieth Century",
    "N5HUDwAAQBAJ": "The Fire Is Upon Us: James Baldwin, William F. Buckley Jr. and the Debate Over Race in America",
    "-lyn2ROnIRIC": "Tolstoy: A Russian Life",
    "3kyPEAAAQBAJ": "Pessoa: A Biography",
    "7akwDwAAQBAJ": "Augustine of Hippo",
    "QHW5DgAAQBAJ": "Young Men and Fire",
    "J3wBEAAAQBAJ": "Furious Hours",
    "x7xbEAAAQBAJ": "Heart of Fire",
    "MOPMDwAAQBAJ": "Before the Coffee Gets Cold",
    "lkA8GLekDbIC": "John Rain series",
    "0koiEAAAQBAJ": "Death in Mud Lick",
    "kRjzDwAAQBAJ": "Crying in H Mart",
    "4iTrDwAAQBAJ": "The Secret to Superhuman Strength",
    "1eZvDwAAQBAJ": "Grant",
    "SqjWAAAAMAAJ": "Freedom",
    "ZK42DwAAQBAJ": "Conflict Is Not Abuse",
    "mhb8LA6vBqwC": "The Tao Is Silent",
    "rPVX4Wqyh4UC": "The Last of the Just",
    "q8xiDwAAQBAJ": "All God’s Dangers: The Life of Nate Shaw",
    "m_kLAAAAYAAJ": "Selected essays",
    "b0yFngEACAAJ": "The Art of Racing in the Rain",
    "GVgBDAAAQBAJ": "Barbarian Days",
    "MepRCwAAQBAJ": "The Underground Railroad",
    "8DZZzgEACAAJ": "Where the Wild Things Are",
    "MF7YpOdr3OoC": "Mary Poppins in the Park",
    "A6sgvgAACAAJ": "The Children of Green Knowe",
    "Ie8kEAAAQBAJ": "Minor Feelings",
    "j1ZxDwAAQBAJ": "Fearing the Black Body",
    "1Nf3FxMIEB8C": "The Chosen",
    "H4XaCwAAQBAJ": "Roll of Thunder, Hear My Cry",
    "paRrDwAAQBAJ": "The Culture of Narcissism",
    "72oOEAAAQBAJ": "Can’t Even",
    "dJNoDQAAQBAJ": "Goodnight Moon",
    "JT5M7q9DlVkC": "A Tale of Two Utopias",
    "cWY2AUUUzVYC": "Coming of Age on Zoloft",
    "zOHTAAAAMAAJ": "A Book of Americans",
    "eSbJAQAAQBAJ": "The Bully Pulpit",
    "Z0dH1DLiSTEC": "The Moviegoer",
    "zgQpAQAAMAAJ": "The Eighth Day of Creation",
    "YqQ4EAAAQBAJ": "Winnie the Pooh",
    "aSqzKUnANM8C": "Creation",
    "GWCUDwAAQBAJ": "CivilWarLand in Bad Decline",
    "KpGNejM3nkEC": "A Visit From the Goon Squad",
    "JyWlEAAAQBAJ": "On Fragile Waves",
    "VmumDwAAQBAJ": "Pilgrim at Tinker Creek",
    "XMm9QZeexV0C": "Grand New Party",
    "xzceAwAAQBAJ": "Resonate",
    "3kWgCgAAQBAJ": "Dragons Love Tacos",
    "jNDyOUZOhyAC": "The House of Mirth",
    "Sn2IyeVuVK0C": "A Tree Grows in Brooklyn",
    "L67rCgAAQBAJ": "Another Brooklyn",
    "CbhnzgEACAAJ": "My Ántonia",
    "xXv-5kTdIaAC": "Then We Came to the End",
    "u6xBJ4XH93AC": "All the King’s Men",
    "Dzqg1TQfK6oC": "Unbought and Unbossed",
    "t4SMEAAAQBAJ": "The Elephant and the Bad Baby",
    "GTd7RAAACAAJ": "The Church Mouse",
    "S4XwDwAAQBAJ": "Tar Beach",
    "LH_mjwEACAAJ": "The Highway Rat",
    "xiNBCgAAQBAJ": "The Complete 8-Book Ramona Collection",
    "lq-EoADbvbUC": "When You Reach Me",
    "KTsuAAAAQBAJ": "The Watsons Go to Birmingham — 1963",
    "wC-xrLWouSIC": "Classic Indian Cooking",
    "9tjZwAEACAAJ": "How to Cook Everything Vegetarian",
    "BHlbAAAAMAAJ": "Lord Emsworth",
    "r723owliVz8C": "The New Book of Middle Eastern Food",
    "08NvDwAAQBAJ": "The Old World Kitchen: The Rich Tradition of European Peasant Cooking",
    "I1X4DwAAQBAJ": "The Optimist’s Telescope",
    "UFWYAAAACAAJ": "The Wuggie Norple Story",
    "URFxDwAAQBAJ": "LikeWar",
    "EtVfCgAAQBAJ": "The Autobiography of Malcolm X",
    "XP1EDQAAQBAJ": "The Very Hungry Caterpillar",
    "16VBDwAAQBAJ": "The Emotional Life of the Toddler",
    "VjBKgiBwyOAC": "The Woman Behind the New Deal",
    "BojUmgEACAAJ": "The Runaway Bunny",
    "PU7PktesGUoC": "Technics and Civilization",
    "8elvDwAAQBAJ": "Andrew Henry’s Meadow",
    "lwAXBQAAQBAJ": "The Great Debate",
    "pPr7nQEACAAJ": "The Upside-Down Constitution",
    "bxyQgM6U5IQC": "Popular Crime",
    "f_0m7WiulUMC": "The Chronicles of Narnia",
    "NkfWDwAAQBAJ": "Short Circuiting Policy",
    "pdnGXwAACAAJ": "The Lorax",
    "qwpjEAAAQBAJ": "Under a White Sky",
    "K_DNDwAAQBAJ": "The Ministry for the Future",
    "EyAstwEACAAJ": "Liquid Reign",
    "muM-nwEACAAJ": "The Three Musketeers",
    "GhAJ2x2coEoC": "The Principles of Representative Government",
    "POF8DwAAQBAJ": "Mortelle Adèle series",
    "OLLLdbxDfAAC": "Red Cavalry",
    "APjXnAAACAAJ": "Stamped From the Beginning",
    "QcWumjEd-HIC": "Dispatches",
    "xO23DwAAQBAJ": "Patriotic Gore",
    "KvAgEAAAQBAJ": "In Love With the World",
    "q7wB2ZHiUlAC": "Loving; Living; Party Going",
    "AF9aAAAAMAAJ": "Scrambled Eggs & Whiskey",
    "B8cvDwAAQBAJ": "Tropic of Squalor",
    "UUlwAAAAQBAJ": "They Lift Their Wings to Cry",
    "AS7zVBa0zIQC": "The Hundred Dresses",
    "oBh3R5UWHWkC": "Caps for Sale",
    "wVqQEAAAQBAJ": "Parable of the Sower",
    "kYeQEAAAQBAJ": "The Color of Law",
    "WuQrDwAAQBAJ": "The Word Collector",
    "n5p7uz4fsU8C": "Double Indemnity",
    "wBE-34_KfcAC": "Master of the Senate",
    "90HozgEACAAJ": "The Great Gatsby",
    "ATl4i59stCMC": "The Complete Stories of Franz Kafka",
    "53kuEeItYtIC": "The Song of the Dodo",
    "YgTpMEUHtmsC": "Global Warming (The Complete Briefing)",
    "9LPqDwAAQBAJ": "Cosmicomics",
    "87UWNi83IrIC": "The Phantom Tollbooth",
    "72QZunsrU3EC": "On Empire, Liberty, and Reform: Speeches and Letters",
    "XE5uDwAAQBAJ": "Reflections on the Revolution in France",
    "IMT5wgEACAAJ": "The American Crisis",
    "IVcrEAAAQBAJ": "The Rights of Man",
    "tUdBDwAAQBAJ": "Conservatism: An Invitation to the Great Tradition",
    "0aDLDwAAQBAJ": "Freedom From the Market: America’s Fight to Liberate Itself From the Grip of the Invisible Hand",
    "1mitDwAAQBAJ": "Social Democratic Capitalism",
    "Wt2eDwAAQBAJ": "The Upswing",
    "g66J6Vzq6EYC": "Normal Accidents",
    "m4fG4aVdvAMC": "Laundry Files series",
    "iaUAJo2Rjj0C": "Merchant Princes series",
    "MzkfAQAAIAAJ": "Plagues and Politics"
}
const obj = {};
const ids = Object.keys(idToTitle).slice(25)
let len = ids.length
let iter = 1
async function fetchId(id,title) {
    const url = generateIdSearchUrl(id)
    
    const response = await fetch(url);
    const data = await response.json();
    const description = await data.volumeInfo.description ? data.volumeInfo.description : undefined
    const averageRating = await data.volumeInfo.averageRating ? data.volumeInfo.averageRating : undefined
    const ratingsCount = await data.volumeInfo.ratingsCount ? data.volumeInfo.ratingsCount : undefined 
    const categories = await data.volumeInfo.categories ? data.volumeInfo.categories : undefined 
    const pageCount = await data.volumeInfo.pageCount ? data.volumeInfo.pageCount : undefined 
    const imageLinks = await data.volumeInfo.imageLinks ? data.volumeInfo.imageLinks : undefined 

    obj[id] = {
description:description,
averageRating:averageRating,
ratingsCount:ratingsCount,
categories:categories,
pageCount:pageCount,
imageLinks:imageLinks,
        title:title
    }
    console.log(`${iter++} / ${len}`)
}
const generateIdSearchUrl = (id, api='https://www.googleapis.com/books/v1/volumes') => 
`${api}/${id}`
let timer = 0
ids.forEach(id=> {
timer += 1500
    setTimeout(
        ()=>{fetchId(id, idToTitle[id]) },timer
        )

})



