const errors = [
    "Free Market",
    "Why We Did It",
    "Famine: A Short History",
    "Mechanique",
    "Witch King",
    "Hitler’s American Friends",
    "Down in New Orleans Billy Sothern",
    "The Neapolitan Novels",
    "Youthquake",
    "Madness and Modernism",
    "Harry Potter and The Methods of Rationality",
    "Stalin: Paradoxes of Power, 1878-1928",
    "Chords of Change (forthcoming 2023)",
    "The Theory of the Leisure Class\"",
    "H is for Hawk",
    "The Weight of Glory",
    "The Lion, the Witch and the Wardrobe",
    "The Epic of Gilgamesh translated",
    "Nobody’s Normal",
    "Man’s Search for Meaning",
    "You Can’t Be Neutral on a Moving Train",
    "Socialism: Past and Future",
    "The Age of Extremes",
    "Classified",
    "Sir Vidia’s Shadow",
    "Stones",
    "Frank: Sonnets",
    "Abortion: Three Perspectives",
    "Free",
    "Suite Française",
    "The Climate War",
    "Blood of Others",
    "The Best and The Brightest",
    "War",
    "Charlotte’s Web",
    "Lord of the Rings",
    "Putin’s World",
    "The Power of Law",
    "Memoirs 1925-1950",
    "India: A Story Through 100 Objects",
    "Dear Parent: Caring for Infants with Respect",
    "Siblings Without Rivalry",
    "Visitors\"",
    "The Weirdest People in the World",
    "Cult of the Constitution",
    "Let’s Get Physical",
    "The Braindead Megaphone",
    "The Three-Body Problem Series",
    "Nicomachean Ethics",
    "The Hebrew Bible, especially Genesis and Exodus",
    "Democracy in America",
    "Making News",
    "Deciding What’s News",
    "Shoutin’ in the Fire",
    "The Adventures of Tintin",
    "The Journal of a Disappointed Man",
    "A Midwife’s Tale",
    "Rebecca’s Revival",
    "Girls and Sex",
    "Boys and Sex",
    "Possibilities",
    "Healthy At Last",
    "You Are The Placebo",
    "Ever Green",
    "Radical Reproductive Justice, edited",
    "Mad As Hell",
    "Ain’t Gonna Let Nobody Turn Me Around",
    "Difference Without Domination",
    "Cars and Trucks and Things That Go",
    "Love in Goon Park",
    "The Narrow Road to the Deep North",
    "Reconstruction",
    "Black Reconstruction in America, 1860-1880",
    "Lazarus",
    "Rise of the Black Panther",
    "Wired for Culture",
    "Champlain’s Dream",
    "Thoughts Without a Thinker",
    "The Old Way",
    "King Solomon’s Ring",
    "Halfway Home: Race, Punishment and the Afterlife of Mass Incarceration",
    "Don Quixote",
    "A Temple of Texts and other work",
    "King Leopold’s Ghost: A Story of Greed, Terror and Heroism in Colonial Africa",
    "Entangled Life: How Fungi Make Our Worlds, Change Our Minds and Shape Our Futures",
    "Other Minds: The Octopus, the Sea and the Deep Origins of Consciousness",
    "Race and Reunion: The Civil War in American Memory",
    "Dirty Work: Essential Jobs and the Hidden Toll of Inequality in America",
    "Poor Queer Studies: Confronting Elitism in the University",
    "Vanguard: How Black Women Broke Barriers, Won the Vote and Insisted on Equality for All",
    "Memorial Drive: A Daughter’s Memoir",
    "Career and Family: Women’s Century-Long Journey Toward Equity",
    "Postwar: A History of Europe Since 1945",
    "Chance and Circumstance: Twenty Years With Cage and Cunningham",
    "Crystal Nights",
    "What to Expect When You’re Expecting Robots",
    "The Overstory",
    "Bring the War Home: The White Power Movement and Paramilitary America",
    "Gods of the Upper Air: How a Circle of Renegade Anthropologists Reinvented Race, Sex and Gender in the Twentieth Century",
    "The Fire Is Upon Us: James Baldwin, William F. Buckley Jr. and the Debate Over Race in America",
    "Tolstoy: A Russian Life",
    "Pessoa: A Biography",
    "Heart of Fire",
    "John Rain series",
    "All God’s Dangers: The Life of Nate Shaw",
    "Selected essays",
    "The Underground Railroad",
    "Where the Wild Things Are",
    "The Chosen",
    "The Culture of Narcissism",
    "Can’t Even",
    "A Tale of Two Utopias",
    "A Book of Americans",
    "Winnie the Pooh",
    "Creation",
    "A Visit From the Goon Squad",
    "Dragons Love Tacos",
    "My Ántonia",
    "The Elephant and the Bad Baby",
    "All the King’s Men",
    "The Complete 8-Book Ramona Collection",
    "The Watsons Go to Birmingham — 1963",
    "Lord Emsworth",
    "The Old World Kitchen: The Rich Tradition of European Peasant Cooking",
    "The Optimist’s Telescope",
    "LikeWar",
    "Five Things We Need to Know About Technological Change",
    "Andrew Henry’s Meadow",
    "The Chronicles of Narnia",
    "Mortelle Adèle series",
    "Stamped From the Beginning",
    "In Love With the World",
    "Loving; Living; Party Going",
    "Scrambled Eggs & Whiskey",
    "The Color of Law",
    "The Complete Stories of Franz Kafka",
    "The Song of the Dodo",
    "Global Warming (The Complete Briefing)",
    "Cosmicomics",
    "On Empire, Liberty, and Reform: Speeches and Letters",
    "Conservatism: An Invitation to the Great Tradition",
    "Freedom From the Market: America’s Fight to Liberate Itself From the Grip of the Invisible Hand",
    "Laundry Files series",
    "Merchant Princes series"
]
